import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/public/styles/globals.css";
import { Toaster } from "react-hot-toast";
import { ShabnamFont } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={ShabnamFont.variable}>
      <Toaster />
      <main className="container min-h-screen flex flex-col items-center justify-center">
        {children}
      </main>
        </body>
    </html>
  );
}
